In [1]:
import numpy as np

a = np.random.rand(4, 20)

In [2]:
a

array([[0.93740713, 0.67294029, 0.57831992, 0.74545231, 0.06513592,
        0.0270842 , 0.33856103, 0.28758971, 0.77159594, 0.74092516,
        0.8708049 , 0.415844  , 0.41254589, 0.52499925, 0.6966012 ,
        0.73079241, 0.78710722, 0.53345653, 0.66054403, 0.09589685],
       [0.90383405, 0.37597055, 0.92410091, 0.65559924, 0.55431935,
        0.35746149, 0.24148605, 0.6990529 , 0.78501207, 0.88349702,
        0.46797279, 0.19928683, 0.91926502, 0.8673235 , 0.7074801 ,
        0.57946182, 0.54504199, 0.17326606, 0.42761696, 0.07857604],
       [0.15691434, 0.972971  , 0.4469981 , 0.72127221, 0.11947965,
        0.63812638, 0.92541641, 0.73789796, 0.87937159, 0.05935069,
        0.72466143, 0.7862644 , 0.33905545, 0.29612634, 0.23790685,
        0.39733909, 0.72668656, 0.33728282, 0.47373004, 0.24550064],
       [0.55170136, 0.25834029, 0.83528532, 0.88061484, 0.04269497,
        0.63994631, 0.74640074, 0.8104626 , 0.06303823, 0.81111871,
        0.48061739, 0.54525619, 0.28938545, 0

In [3]:
a.shape

(4, 20)

In [7]:
stdev = a.std(axis=0)

In [8]:
np.argsort(stdev)

array([ 3, 16, 15, 18, 17, 19, 10,  2,  7,  4, 11, 13, 14, 12,  5,  1,  6,
        0,  8,  9])

In [12]:
np.argsort(stdev)[:10]

array([ 3, 16, 15, 18, 17, 19, 10,  2,  7,  4])

In [15]:
weight_matrix = np.zeros(20)

for item in np.argsort(stdev)[:10]:
    weight_matrix[item] = 1

In [16]:
weight_matrix

array([0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
       1., 1., 1.])

In [9]:
stdev[3]

0.08187726974527265

In [10]:
stdev[16]

0.09432320934040721

In [11]:
stdev[9]

0.32971660158193417